words = [
    "alnum",
    "ansi",
    "appstream",
    "arrowsize",
    "ascii",
    "asdict",
    "asyncio",
    "atexit",
    "autoapi",
    "autodoc",
    "bysource",
    "cdef",
    "certbot",
    "chardet",
    "chdir",
    "cimport",
    "cinit",
    "cmpkey",
    "coissac",
    "cpython",
    "csi",
    "ctypes",
    "cwd",
    "cygwin",
    "cython",
    "cythonize",
    "daemonized",
    "dataclasses",
    "dbus",
    "decref",
    "deepcopy",
    "delattr",
    "delitem",
    "devel",
    "devnull",
    "dfoo",
    "distutils",
    "docstrings",
    "editables",
    "emscripten",
    "esc",
    "filesx",
    "firstlineno",
    "flatpak",
    "folderid",
    "fontcolor",
    "fontsize",
    "fspath",
    "functorial",
    "furo",
    "getitem",
    "getstate",
    "groupindex",
    "hostnames",
    "hresult",
    "idna",
    "incref",
    "instancecheck",
    "instanciated",
    "interprocess",
    "intersphinx",
    "ior",
    "issubclass",
    "jse",
    "knownfolderid",
    "kwds",
    "ldh",
    "ldhu",
    "ldu",
    "lingamneni",
    "lpt",
    "maxsize",
    "metaclass",
    "modindex",
    "mro",
    "msc",
    "mul",
    "multiton",
    "mureq",
    "neginf",
    "ngettext",
    "nodeenv",
    "npx",
    "nthreads",
    "objc",
    "oem",
    "opt'in",
    "orderable",
    "osc",
    "pathsep",
    "pdm",
    "penwidth",
    "pgid",
    "pidfile",
    "plc",
    "plr",
    "popitem",
    "ppsz",
    "prn",
    "purelib",
    "pwstr",
    "pyi",
    "pypi",
    "pyproject",
    "pythonic",
    "rankdir",
    "retcode",
    "rst",
    "ruf",
    "sdist",
    "setattr",
    "setdefault",
    "setitem",
    "setsid",
    "setstate",
    "setuptools",
    "sgr",
    "sourcery",
    "ssize",
    "subclassed",
    "tdiv",
    "tnum",
    "truediv",
    "tty",
    "typehints",
    "unc",
    "undoc",
    "unhashable",
    "unice",
    "uti",
    "wasi",
    "weakref",
    "winexec",
    "winpath",
    "wintypes",
    "workpath",
    "wsh",
    "xdg",
]
