#####################################################
# Project Metadatas
#####################################################
[project]
name = "standard-deluxe"
description = "A handfull collection of python utilities."
authors = [{ name = "Gilles Coissac", email = "gilles@ideographe.fr" }]
license = { text = "GPL-3.0" }
readme = "README.md"
keywords = []
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
  "Typing :: Typed",
]

urls.homepage      = "https://github.com/gravures/standard-deluxe"
urls.repository    = "https://github.com/gravures/standard-deluxe"
urls.documentation = "https://github.com/gravures/standard-deluxe"
urls.issue         = "https://github.com/gravures/standard-deluxe/issues"

dynamic         = ["version"]
requires-python = ">=3.9"
dependencies    = []

#####################################################
# PDM
#####################################################
[build-system]
requires      = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.build]
package-dir      = "src"
includes         = ["src/deluxe/"]
editable-backend = "path"

[tool.pdm.version]
source         = "scm"
write_to       = "deluxe/_version.py"
write_template = "__version__ = '{}'"

[tool.pdm.dev-dependencies]
dev = [
  "ruff>=0.5",
  "basedpyright>=1.15",
  "pre-commit>=3.7.0",
  "tox-pdm>=0.7.2",
  "dead>=1.5.2",
  "pretty-errors>=1.2.25",
]
monorepo = ["pdm>=2.16.1", "pdm-backend>=2.3.1"]
test = ["pytest", "hypothesis", "coverage[toml]", "tox>=4.0", "editables>=0.5"]

#####################################################
# PDM MONOREPO PACKAGES
#####################################################
[tool.pdm.monorepo.packages.factory]
includes            = ["src/deluxe/factory"]
excludes            = ["tests"]
project.name        = "deluxe-factory"
project.description = "Standard-deluxe factory module."
project.classifiers = ["Development Status :: 3 - Beta"]

[tool.pdm.monorepo.packages.files]
includes            = ["src/deluxe/files.py"]
excludes            = ["tests"]
project.name        = "deluxe-files"
project.description = "Standard-deluxe files module."
project.classifiers = ["Development Status :: 3 - Alpha"]

[tool.pdm.monorepo.packages.importers]
includes            = ["src/deluxe/importers.py"]
excludes            = ["tests"]
project.name        = "deluxe-importers"
project.description = "Standard-deluxe importers module."
project.classifiers = ["Development Status :: 3 - Alpha"]

[tool.pdm.monorepo.packages.mappings]
includes            = ["src/deluxe/mappings.py"]
excludes            = ["tests"]
project.name        = "deluxe-mappings"
project.description = "Standard-deluxe mappings module."
project.classifiers = ["Development Status :: 4 - Beta"]

#####################################################

#####################################################
# PDM SCRIPTS
#####################################################
[tool.pdm.scripts]
traceback   = "_traceback.py"
xrequire    = "pdm export -f requirements -o requirements.txt"
test        = "pytest -s -v -k {args}"
test_all    = "coverage run -m pytest"
test_typing = "pdm run basedpyright --stats ./src/deluxe"
test_cover  = "coverage report"
tox_testme  = "tox --develop -r -e py"
pc_init     = "pre-commit install --install-hooks"
pc_update   = "pre-commit autoupdate"
pc_check    = { env = { "SKIP" = "basedpyright" }, cmd = "pre-commit run --all-files" }
dead        = "dead"
pc_clean    = "pre-commit clean && pre-commit gc"
deps        = "pdm list --fields name,groups,version,licenses,homepage --sort groups,name,licenses --exclude :sub"

[tool.pdm.scripts.pc_safety]
composite = ["xrequire", "pre-commit run python-safety-dependencies-check"]

[tool.pdm.scripts.suite]
composite = [
  "echo '\f'",
  "pdm show",
  "echo '\nDEPS'",
  "deps",
  "echo '\nPRE-COMMIT'",
  "pc_check",
  "echo '\nTYPING'",
  "test_typing",
  "echo '\nDEAD CODE'",
  "dead",
  "echo '\nCOVERAGE'",
  "test_cover",
]
