#####################################################
# Project Metadatas
#####################################################
[project]
name = "standard-deluxe"
description = "A hanfull collection of python utilities."
authors = [{ name = "Gilles Coissac", email = "gilles@ideographe.fr" }]
license = { text = "GPL-3.0" }
readme = "README.md"
keywords = []
classifiers = [
  "Intended Audience :: Developers",
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
  "Operating System :: OS Independent",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3 :: Only",
  "Typing :: Typed",
]
requires-python = ">=3.9"
dependencies = []
dynamic = ["version"]

[project.urls]
homepage      = "https://github.com/gravures/standard-deluxe"
repository    = "https://github.com/gravures/standard-deluxe"
documentation = "https://github.com/gravures/standard-deluxe"
issue         = "https://github.com/gravures/standard-deluxe/issues"

[project.scripts]

#####################################################
# PDM
#####################################################
[build-system]
requires      = ["pdm-backend"]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true
plugins      = []

[tool.pdm.build]
package-dir      = "src"
editable-backend = "editables"

[tool.pdm.options]

[tool.pdm.version]
source         = "scm"
write_to       = "deluxe/_version.py"
write_template = "__version__ = '{}'"

[tool.pdm.dev-dependencies]
dev = [
  "ruff==0.4.1",
  "basedpyright==1.10.3",
  "pre-commit==3.7.0",
  "tox-pdm>=0.7.2",
  "dead>=1.5.2",
  "pretty-errors>=1.2.25",
]

test = ["pytest", "hypothesis", "coverage[toml]", "tox>=4.0"]

[tool.pdm.scripts]
traceback   = "_traceback.py"
xrequire    = "pdm export -f requirements -o requirements.txt"
test        = "pytest -s -v -k {args}"
test_all    = "coverage run -m pytest"
test_typing = "pdm run basedpyright --stats ./src/deluxe"
test_cover  = "coverage report"
tox_testme  = "tox --develop -r -e py"
pc_init     = "pre-commit install --install-hooks"
pc_update   = "pre-commit autoupdate"
pc_check    = { env = { "SKIP" = "basedpyright" }, cmd = "pre-commit run --all-files" }
dead        = "dead"
pc_clean    = "pre-commit clean && pre-commit gc"
deps        = "pdm list --fields name,groups,version,licenses,homepage --sort groups,name,licenses --exclude :sub"

[tool.pdm.scripts.pc_safety]
composite = ["xrequire", "pre-commit run python-safety-dependencies-check"]

[tool.pdm.scripts.suite]
composite = [
  "echo '\f'",
  "pdm show",
  "echo '\nDEPS'",
  "deps",
  "echo '\nPRE-COMMIT'",
  "pc_check",
  "echo '\nTYPING'",
  "test_typing",
  "echo '\nDEAD CODE'",
  "dead",
  "echo '\nCOVERAGE'",
  "test_cover",
]
