from __future__ import annotations  # noqa: PYI044

from collections.abc import Iterator
from types import NotImplementedType
from typing import Any, ClassVar, Literal, Never, Protocol

class _UnsetMeta(type):
    def __delattr__(cls, name: str, /) -> None: ...
    def __setattr__(cls, name: str, value: Any, /) -> None: ...

# UnsetType: type
UnsetType = type("UnsetType", (NotImplementedType,), {})
"""The type of the Unset singleton."""

# Unset: UnsetType
class Unset(metaclass=UnsetType):
    """The `Unset` singleton is design to act as a sentinel type.

    It could be assigned to any type and mimic as far as possible `None`.
    """

    def __call__(self) -> Never: ...
    def __bool__(self) -> Literal[False]: ...

class FrozenProtocol(Protocol):
    __frozen__: ClassVar[tuple[str, ...]]

class Frozen(FrozenProtocol):  # pyright: ignore[reportImplicitAbstractClass]
    def __iter__(self) -> Iterator[object]: ...
    def __hash__(self) -> int: ...
    def __eq__(self, value: object, /) -> bool: ...
    def __contains__(self, value: object) -> bool: ...
    def __getitem__(self, index: int) -> object: ...
    def __len__(self) -> int: ...
    def count(self, value: object) -> int: ...
    def index(self, value: object, start: int = 0, stop: int | None = None) -> int: ...
    def as_dict(self) -> dict[str, object]: ...
