# Generated by Qodo Gen
from __future__ import annotations

import os
from pathlib import Path, PurePosixPath, PureWindowsPath

import pytest  # noqa: F401
from deluxe.files import is_winpath


POSIX: bool = os.name == "posix"


def test_windows_path_with_drive_letter():
    test_path = "C:\\Users\\test"
    assert is_winpath(test_path) is True


def test_empty_path():
    test_path = ""
    assert is_winpath(test_path) is not POSIX


def test_pure_windows_path_instance():
    test_path = PureWindowsPath("C:\\Users\\test")
    assert is_winpath(test_path) is True


def test_non_pureposixpath():
    test_path = "C:\\Program Files\\test"
    assert is_winpath(test_path) is True


def test_pureposixpath():
    test_path = PurePosixPath("/home/user/test")
    assert is_winpath(test_path) is False


def test_relative_path():
    test_path = "relative/path/to/file"
    assert is_winpath(test_path) is False


def test_mixed_slashes_path():
    test_path = "C:/Users\\test"
    assert is_winpath(test_path) is True


def test_unc_path():
    test_path = r"\\server\share\folder"
    assert is_winpath(test_path) is True


def test_file_protocol_path():
    test_path = "file://C:/Users/test"
    assert is_winpath(test_path) is False


def test_path_objects_vs_string_inputs():
    # Test with a Windows path object
    win_path_obj = PureWindowsPath("C:\\Users\\test")
    assert is_winpath(win_path_obj) is True

    # Test with a POSIX path object
    posix_path_obj = PurePosixPath("/home/user/test")
    assert is_winpath(posix_path_obj) is False

    # Test with a Windows path string
    win_path_str = "C:\\Users\\test"
    assert is_winpath(win_path_str) is True

    # Test with a POSIX path string
    posix_path_str = "/home/user/test"
    assert is_winpath(posix_path_str) is False


def test_absolute_vs_relative_path_handling():
    # sourcery skip: extract-duplicate-method, inline-variable
    # Test with absolute Windows path
    absolute_windows_path = "C:\\Program Files\\test"
    assert is_winpath(absolute_windows_path) is True

    # Test with relative Windows path
    relative_windows_path = "Program Files\\test"
    assert is_winpath(relative_windows_path) is False
    assert is_winpath(PureWindowsPath(relative_windows_path)) is True

    # Test with absolute POSIX path
    absolute_posix_path = "/usr/local/bin"
    assert is_winpath(absolute_posix_path) is False

    # Test with relative POSIX path
    relative_posix_path = "usr/local/bin"
    assert is_winpath(relative_posix_path) is False


# Test case sensitivity of drive letters
def test_case_sensitivity_of_drive_letters():
    # Test with Windows path containing lowercase drive letter
    lowercase_drive_path = "c:\\Users\\test"
    assert is_winpath(lowercase_drive_path) is True

    # Test with Windows path containing uppercase drive letter
    uppercase_drive_path = "C:\\Users\\test"
    assert is_winpath(uppercase_drive_path) is True


# Test paths with Unicode characters
def test_unicode_windows_path():
    # Test with Windows path containing Unicode characters
    test_path = "C:\\Users\\测试"
    assert is_winpath(test_path) is True


def test_edge_cases_path():
    test = is_winpath(Path("/project/code\\joli.py"))
    assert test is False if POSIX else True

    test = is_winpath(Path("joli.py"))
    assert test is False if POSIX else True

    test = is_winpath(Path(r"project\code\joli.py"))
    assert test is False if POSIX else True

    test = is_winpath(Path(r"/project/code\ joli.py"))
    assert test is False

    test = is_winpath(Path("joli.py"))
    assert test is False

    test = is_winpath(Path("joli.py"))
    assert test is False

    test = is_winpath(Path(r"/project/code\ joli.py"))
    assert test is False

    test = is_winpath(Path(r"joli\ ouf.py"))
    assert test is False

    test = is_winpath(Path(r"/joli\ ouf.py"))
    assert test is False


def test_edge_cases_strpath():
    test = is_winpath("\\project\\code.py")
    assert test is False if POSIX else True

    test = is_winpath("c:\\project\\code\\joli.py")
    assert test is True

    test = is_winpath("file:\\project\\code\\joli.py")
    assert test is False if POSIX else True

    test = is_winpath(r"file:/project\code\joli.py")
    assert test is False if POSIX else True

    test = is_winpath("file:/project/code/joli.py")
    assert test is False if POSIX else True

    test = is_winpath("a:/project/code/joli.py")
    assert test is True

    test = is_winpath("file:joli.py")
    assert test is False if POSIX else True

    test = is_winpath("file:/joli.py")
    assert test is False if POSIX else True

    test = is_winpath("file:\\joli")
    assert test is False if POSIX else True

    test = is_winpath("\\joli")
    assert test is False if POSIX else True

    test = is_winpath("joli.py")
    assert test is False if POSIX else True
