name: Test
on:
  pull_request:
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - '*.lock'
  workflow_dispatch:

jobs:
  testing:
    strategy:
      matrix:
        python-version: ['3.11', '3.12', '3.13', '3.14']
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: install mise with Python ${{ matrix.python-version }}
        uses: jdx/mise-action@v4
        with:
          version: 2026.6.14
          install: true
          cache: true
          tool_versions: python ${{ matrix.python-version }}

      - name: install testing dependencies
        run: |
          mise run project:sync --group test

      - name: run tests suite with coverage
        env:
          COVERAGE_FILE: ".coverage.${{ matrix.python-version }}.${{ matrix.os }}"
        run: |
          mise run typecheck
          mise run test:cover

      - name: store coverage file
        if: ${{ matrix.os }} == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}-${{ matrix.os }}
          path: .coverage.${{ matrix.python-version }}.${{ matrix.os }}
          include-hidden-files: true

      - name: minimize uv cache
        run: uv cache prune --ci

  coverage:
    needs: [testing]
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      actions: read

    steps:
      - name: checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: gets coverage db
        uses: actions/download-artifact@v4
        id: download
        with:
          pattern: coverage-*-*
          merge-multiple: true
          # path: artifacts

      # - name: inspect downloaded artifacts
      #   run: |
      #     echo "Artifacts dir listing (if present):"
      #     ls -la artifacts || true
      #     echo "Coverage files found under artifacts:"
      #     find artifacts -type f -name ".coverage.*" -print || true

      # - name: move coverage files to repository root
      #   run: |
      #     find artifacts -type f -name ".coverage.*" -exec mv -t . {} +
      #   shell: bash

      - name: create coverage comment
        id: coverage_comment
        uses: py-cov-action/python-coverage-comment-action@v4.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_PR_RUN_ID: ${{ github.event.workflow_run.id }}
          COVERAGE_DATA_BRANCH: python-coverage
          COMMENT_ARTIFACT_NAME: python-coverage
          COMMENT_FILENAME: python-coverage.txt
          MERGE_COVERAGE_FILES: true

      - name: store pull request comment to be posted
        uses: actions/upload-artifact@v4
        if: steps.coverage_comment.outputs.COMMENT_FILE_WRITTEN == 'true'
        with:
          name: python-coverage
          path: python-coverage.txt
